{
 "title": "cnw global",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Assoc per SSID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnDot11EssNumberOfMobileStations",
     "legendFormat": "{{bsnDot11EssSsid}}"
    }
   ]
  },
  {
   "title": "Assoc per Location",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(loc) (label_replace(bsnApIfNoOfUsers, \"loc\", \"$1\", \"bsnAPName\", \"^ap-(.+?)-.*$\"))",
     "legendFormat": "{{loc}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"^gw-.*$\",ifName=~\"^(?:Gi).+0.[0-9]$\"}[1m]) * 8",
     "legendFormat": "{{instance}}: {{ifName}} Out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=~\"^gw-.*$\",ifName=~\"^(?:Gi).+0.[0-9]$\"}[1m]) * 8",
     "legendFormat": "{{instance}}: {{ifName}} In"
    }
   ]
  },
  {
   "title": "DNS Cache Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(unbound_cache_misses_total[1m]))",
     "legendFormat": "{{instance}}: Miss"
    },
    {
     "expr": "sum by(instance) (rate(unbound_cache_hits_total[1m]))",
     "legendFormat": "{{instance}}: Hit"
    }
   ]
  },
  {
   "title": "Bandwidth Stack",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{instance=~\"^gw-.*$\",ifName=~\"^(?:Gi).+0.[0-9]$\"}[1m]) * 8",
     "legendFormat": "{{instance}}: {{ifName}} Out"
    },
    {
     "expr": "irate(ifHCInOctets{instance=~\"^gw-.*$\",ifName=~\"^(?:Gi).+0.[0-9]$\"}[1m]) * 8",
     "legendFormat": "{{instance}}: {{ifName}} In"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (irate(unbound_queries_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kea_dhcp4_addresses_total ", "legendFormat": "{{subnet}} Total" },
    {
     "expr": "kea_dhcp4_addresses_assigned_total",
     "legendFormat": "{{subnet}} Assigned"
    },
    {
     "expr": "kea_dhcp4_addresses_declined_total",
     "legendFormat": "{{subnet}} Declined"
    },
    {
     "expr": "kea_dhcp4_addresses_reclaimed_total",
     "legendFormat": "{{subnet}} Reclaimed"
    },
    {
     "expr": "kea_dhcp4_addresses_declined_reclaimed_total",
     "legendFormat": "{{subnet}} Declined&Reclaimed"
    }
   ]
  }
 ]
}