{
 "title": "cnw location",
 "time": { "from": "2019-04-16T23:00:00.000Z", "to": "2019-04-20T12:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "haa,hab,hac,had,lb1,lb2,lb3,lb4,lb5,ex2,gya,bck,rbc"
   }
  ]
 },
 "panels": [
  {
   "title": "Assocs per AP (5 GHz)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnApIfNoOfUsers{bsnAPIfType=\"2\",bsnAPName=~\".*-($location)-.*\"}",
     "legendFormat": "{{bsnAPName}}.{{bsnAPIfSlotId}}"
    }
   ]
  },
  {
   "title": "Assocs per AP (2.4 GHz)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnApIfNoOfUsers{bsnAPIfType=\"1\",bsnAPName=~\".*-($location)-.*\"}",
     "legendFormat": "{{bsnAPName}}.{{bsnAPIfSlotId}}"
    }
   ]
  },
  {
   "title": "Channel Utilizaiton",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnAPIfLoadChannelUtilization{bsnAPName=~\".*-($location)-.*\",bsnAPIfSlotId=\"1\"}",
     "legendFormat": "{{bsnAPName}} {{bsnAPIfType}}.{{bsnAPIfSlotId}}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnAPIfPhyChannelNumber{bsnAPName=~\"^.*-($location)-.*$\"}",
     "legendFormat": "{{bsnAPName}} {{bsnAPIfType}}.{{bsnAPIfSlotId}}"
    }
   ]
  },
  {
   "title": "Power Level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bsnAPIfPhyTxPowerLevel{bsnAPName=~\"^.*-($location)-.*$\"}",
     "legendFormat": "{{bsnAPName}} {{bsnAPIfType}}.{{bsnAPIfSlotId}}"
    }
   ]
  },
  {
   "title": "bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifInOctets{instance=~\"^es-($location)-.+$\",ifAlias=\"upstream\"}[1m]) *8",
     "legendFormat": "{{instance}} {{ifDescr}} In"
    },
    {
     "expr": "irate(ifOutOctets{instance=~\"^es-($location)-.+$\",ifAlias=\"upstream\"}[1m]) *8",
     "legendFormat": "{{instance}} {{ifDescr}} Out"
    }
   ]
  }
 ]
}